---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-gpustat-prod
  labels:
    app: k8s-gpustat-prod
spec:
        #replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: k8s-gpustat-prod
  template:
    metadata:
      labels:
        app: k8s-gpustat-prod
    spec:
      nodeSelector:
        gpushare: "false"
      hostPID: true
      #      priorityClassName: "system-node-critical"
      containers:
        - name: k8s-gpustat-prod
          image: registry.local:5000/gpustat_web_nv:1.0
          ports:
            - containerPort: 5555
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: 5555
#            initialDelaySeconds: 30
#            timeoutSeconds: 30
          imagePullPolicy: Always
          env:
            - name: MYSQL_DB_HOST
              value: mysql-service
            - name: MYSQL_DB_PORT
              value: "3306"
            - name: MYSQL_DB_USER
              value: root
            - name: MYSQL_DB_PASSWORD
              value: '12345'
            - name: KAFKA_BROKER
              value: kafka.default.svc.cluster.local
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-gpustat-prod
  namespace: default
  labels:
    app: k8s-gpustat-prod
spec:
  ports:
    - port: 5555
      targetPort: 5555
  selector:
    app: k8s-gpustat-prod
  type: ClusterIP
